name: Build CI

on: [push, pull_request]

jobs:
  macos:
    uses: rime/librime/.github/workflows/macos-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}

  windows:
    uses: ./.github/workflows/windows-build.yml

  linux:
    uses: HuangJian/librime/.github/workflows/linux-build.yml@linux-with-plugins
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}
