name: Build CI

on: [push, pull_request]

jobs:
  macos:
    uses: rime/librime/.github/workflows/macos-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}

  windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      repository: HuangJian/librime
      ref: windows-llvm20 # The branch, tag or SHA to checkout
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}

  linux:
    uses: HuangJian/librime/.github/workflows/linux-build.yml@linux-with-plugins
    with:
      repository: HuangJian/librime
      ref: linux-with-plugins # The branch, tag or SHA to checkout
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}
