name: Build CI

on: [push, pull_request]

jobs:
  macos:
    uses: rime/librime/.github/workflows/macos-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}

  windows:
    uses: HuangJian/librime/.github/workflows/windows-build.yml@master
    with:
      repository: HuangJian/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}
      matrix: # build with clang only
        compiler: [clang]
        arch: [x64]
        include:
          - { compiler: clang, cc: clang, cxx: clang++ }
