name: Build CI

on: [push, pull_request]

jobs:
  macos:
    uses: rime/librime/.github/workflows/macos-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}

  windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      repository: HuangJian/librime
      ref: ci-build-librime-qjs # The branch, tag or SHA to checkout
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}

  linux:
    uses: HuangJian/librime/.github/workflows/linux-build.yml@ci-build-librime-qjs
    with:
      repository: HuangJian/librime
      ref: ci-build-librime-qjs # The branch, tag or SHA to checkout
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}
