name: Commit CI

on:
  push:
    branches:
      - '*'         # This will match all branches
      - '!main'   # Then exclude main
    tags:
      - '![0-9]+.*'
  pull_request:


jobs:
  lint:
    runs-on: macos-14
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
      - name: Install latest lang-format
        run: brew update && brew install clang-format
      - name: Code style lint
        run: bash ./tools/clang-format.sh lint
      - name: Install latest nodejs
        run: brew update && brew install nodejs
      - name: Check rime.d.ts
        run: (cd ./tools; node ./check-api-coverage.js)
  # macos:
  #   needs: lint
  #   uses: rime/librime/.github/workflows/macos-build.yml@master
  #   with:
  #     repository: rime/librime
  #     rime_plugins: ${{ github.repository }}@${{ github.ref_name }}
