name: Development CI (linters)

on:
  push:
    branches:
      - '*'         # This will match all branches
      - '!main'     # Then exclude main
    tags:
      - '![0-9]+.*'
  pull_request:


jobs:
  lint:
    runs-on: macos-15
    steps:

      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branch for diff base
        run: git fetch --no-tags origin main:refs/remotes/origin/main

      - name: Checkout submodules/dependencies
        run: bash ./action-install.sh

      - name: Configure build environment
        run: |
          brew update
          brew install cmake llvm clang-format nodejs
          echo "$(brew --prefix llvm)/bin" >> "${GITHUB_PATH}"

      - name: Code format lint
        run: bash ./tools/clang-format.sh lint

      - name: Code style lint on modified files
        run: bash ./tools/clang-tidy.sh modified

      - name: Check rime.d.ts
        run: (cd ./tools; node ./check-api-coverage.js)
